### ISSUE TITLE
Fill with gradient

### ISSUE THREAD

**Issue by ilyaChuk2004** [PavelLaptev/squircle-houdini-css#10]
Hello. I tried to use like this. 

```
--squircle-smooth: 0.4;
--squircle-radius: 12;
--squircle-fill: linear-gradient(24deg, #00000094 0%, #3d3d3d00 100%);
background: paint(squircle);
```

But I just get just a black fill. Can a gradient be used with ` background: paint (squircle)`?

**Comment by PavelLaptev** [comment]
@ilyaChuk2004 you can use `gradient` with `mask-image: paint(squircle);`
https://codepen.io/PavelLaptev/pen/BadqpVg
