### ISSUE TITLE
Doesn't work with <a></a> tag

### ISSUE THREAD

**Issue by diziant** [PavelLaptev/squircle-houdini-css#11]
Hello, I tried to use `<a></a>` tag and it doesn't work.

When I use any html elements it works, but if I use `<a></a>` tag and add href=' ' attribute my element vanishes.

I̶ ̶k̶n̶o̶w̶ ̶t̶h̶a̶t̶ ̶I̶ ̶c̶a̶n̶ ̶u̶s̶e̶ ̶i̶n̶n̶e̶r̶ ̶e̶l̶e̶m̶e̶n̶t̶ ̶f̶o̶r̶ ̶w̶i̶t̶h̶,̶ ̶b̶u̶t̶ ̶i̶t̶'̶s̶ ̶n̶o̶t̶ ̶a̶ ̶g̶o̶o̶d̶ ̶w̶a̶y̶ -> It doesn't work too with tag `<a></a>`

**Comment by PavelLaptev** [comment]
Hi @diziant 
please check these issues
https://github.com/PavelLaptev/squircle-houdini-css/issues/2
https://github.com/PavelLaptev/squircle-houdini-css/issues/4
