### ISSUE TITLE
Does not work in next js app

### ISSUE THREAD

**Issue by demidmalyanov** [PavelLaptev/squircle-houdini-css#14]
I curious why the library doesnt work in my next js home page. Scripts are loading before page is interactive and is visible but not actually rendered squircles.

**Comment by rohitpotato** [comment]
@demidmalyanov did you figure out the solution? I am facing a similar issue.

**Comment by demidmalyanov** [comment]
> @demidmalyanov did you figure out the solution? I am facing a similar issue.

Yes, I just add Script component from next/script on my index page.
Just like this
`
 <Script
        strategy="beforeInteractive"
        dangerouslySetInnerHTML={{
          __html: `
          if ("paintWorklet" in CSS) {
            CSS.paintWorklet.addModule(
              "https://www.unpkg.com/css-houdini-squircle/squircle.min.js"
            );
          }
  `,
        }}
      />

`

**Comment by rohitpotato** [comment]
Turns out it was an issue my next version, updating to latest 12 fixed this for me.
