### ISSUE TITLE
Outline disappears when wrapping element in a <a> tag

### ISSUE THREAD

**Issue by lvwrence** [PavelLaptev/squircle-houdini-css#2]
Hey there, I really like the simplicity of this library. However, I found that when wrapping my squircle elements in an `<a href="www.google.com">` tag, the squircle outline disappears. Do you know how to get around this?

**Comment by PavelLaptev** [comment]
Hi @lvwrence 
Thanks, that's a really good question. The answer is still a mystery to me, I even ask for an answer on [stackoverflow](https://stackoverflow.com/questions/67253145/css-paint-api-doesnt-work-with-link-a-elements). Might be someone can shed a light on it.

But at the moment you can wrap your link with a `div`. Also it will work with the outline property, but you need to use `:pseudo` element.

Here is a working example:
https://codepen.io/PavelLaptev/pen/wvgNXox

**Comment by lvwrence** [comment]
Thanks, this should work!
