### ISSUE TITLE
Default to `--squircle-smooth: 1`

### ISSUE THREAD

**Issue by wooorm** [PavelLaptev/squircle-houdini-css#3]
Only adding `mask: paint(squircle)` gives a quite interesting result, but perhaps not what folks expect for squircles:

<img width="965" alt="Screen Shot 2021-11-02 at 09 28 48" src="https://user-images.githubusercontent.com/944406/139811663-75b282cd-97cb-4237-8847-eb7aface0993.png">

Defaulting `--squircle-smooth: 1` though, looks more like what I’d expect:

<img width="1009" alt="Screen Shot 2021-11-02 at 09 29 49" src="https://user-images.githubusercontent.com/944406/139811796-4eaecd2d-e099-4612-b4ac-8e13d285dafb.png">

**Comment by wooorm** [comment]
This seems to be documented as defaulting to `1`, but I’m not seeing that? 🤔

**Comment by PavelLaptev** [comment]
@wooorm good idea. I'll check it

**Comment by wooorm** [comment]
Sweet!

My guess is that:

- [this line](https://github.com/PavelLaptev/squircle-houdini-css/blob/72562f313b90f4124abc645072f2f7348d0dafd0/build/paintWorklet/squircle.js#L80) evaluates `undefined * 10` to `NaN`
- resulting in [this condition](https://github.com/PavelLaptev/squircle-houdini-css/blob/72562f313b90f4124abc645072f2f7348d0dafd0/build/paintWorklet/squircle.js#L90) passing
- resulting in `NaN` being [returned here](https://github.com/PavelLaptev/squircle-houdini-css/blob/72562f313b90f4124abc645072f2f7348d0dafd0/build/paintWorklet/squircle.js#L94)

**Comment by PavelLaptev** [comment]
Updated https://www.unpkg.com/browse/css-houdini-squircle@0.2.0/squircle.min.js
